# Generated by Django 4.2 on 2023-07-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resim', models.ImageField(upload_to='bal_resmi/')),
                ('kayit_tarihi', models.DateField(auto_now_add=True)),
                ('isActive', models.BooleanField()),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
